### ISSUE TITLE
Discord Twich Embed window too large

### ISSUE THREAD

**Issue by Zero-Shift** [theoriginalcamper/Better-GDQ#2]
Latest version, both straight from the Chrome store and unpacked extensions from Github.
Chrome 63.0.3239.132 x64

When viewing embedded Twitch player in Chrome, the player takes up too much space so half of chat is unreadable. Same result in Incognito mode with no other extensions enabled.

![image](https://user-images.githubusercontent.com/1923129/34843030-f33e6470-f6d2-11e7-97c5-69377f7fa8df.png)

**Comment by theoriginalcamper** [comment]
Sorry I need to add tooltip to the build for the next event. I used to be able to close the members list for the Discord server programmatically, but that's no longer the case so you've got to close it manually. If you close the members list, the chat fills in it's space to the right, which makes it completely visible.
