### ISSUE TITLE
Auto-collapse members sidebar when opening twitch embed

### ISSUE THREAD

**Issue by connorshea** [theoriginalcamper/Better-GDQ#3]
Can the members sidebar be auto-collapsed when the stream is opened? I'm not sure if this is a problem on larger screens :)

<img width="1435" alt="screen shot 2018-06-24 at 7 20 17 pm" src="https://user-images.githubusercontent.com/2977353/41826039-c5239618-77e3-11e8-8e2c-56776bceedd1.png">

**Comment by theoriginalcamper** [comment]
Recent changes to Discord have made this possible again. For several events running, Discord seemingly blocked every way of simulating a click, but now that's no longer the case.

Fixed in 3.0.1
